### ISSUE TITLE
Publikationen (Gius 2015, Hrsg. auf englisch)

### ISSUE THREAD

**Issue by evelyn-gius** [evelyn-gius/evelyn-gius.github.io#4]
- in beiden Sprachen steht bei Gius 2015 "(Hrsg.)"  nach dem Namen. Das sollte da nicht stehen.
- im Englischen fehlt der Abschnitt "Monographie" ("Book")
- im Englischen steht für Herausgeber:innen  "(Hrsg.)" statt "(eds.)" bzw. "(ed.)" bei einzelnen Personen. Das muss evtl. im Export nochmal geprüft werden

**Comment by Momamari** [comment]
Bitte überprüfen

**Comment by evelyn-gius** [comment]
Sieht gut aus! Nur noch zwei kleine Dinge: Die ersten beiden herausgegebenen Publikationen (Besold et al. und Gius, Willand, Reiter) haben kein "(Hrsg.)" bzw. "(eds.)" und bei der dritten ist jeweils ein Punkt vor dem  "(Hrsg.)" bzw. "(eds.)", der da nicht hingehört.
