### ISSUE TITLE
Vereinheitlichung Seitenpfade

### ISSUE THREAD

**Issue by evelyn-gius** [evelyn-gius/evelyn-gius.github.io#6]
- alle Seiten sollten auf deutsch und englisch denselben Namen im Pfad haben (also research, talks, publications)
- gibt es darüber hinaus noch Punkte, an denen mehr EInehitlchkeit hilfreich wäre?
- fürs Lab übernehmen?

**Comment by Momamari** [comment]
Eigentlich sind alle Seitenpfade hier gleich, oder? - außer das "publications" "Publikationen" hieß. Das habe ich jetzt geändert

**Comment by evelyn-gius** [comment]
Stimmt, sorry. Mich haben dann wohl die deutschen Namen gestört ;-) Die gibt es auch beim Lab. 
Neuer Versuch: bitte überall ein-Wort-Dinger auf Englisch, damit auch die URLs schön sind. Also in beiden Sprachen
- bei meiner Seite:  das talks2 zu talks machen 
- im lab 
  - projekte  --> projects
  - lab_team --> team
  - pubs_sorted --> pubs
